title: Damien Tze-In Koh
logo: ./headshot.jpg
description: Northwestern University Class of 2025 | B.S. in Computer Engineering, M.S. in Electrical Engineering specializing in Robotics
theme: jekyll-theme-minimal
