title: Damien Tze-In Koh
logo: ./headshot.jpg
description: B.S. in Computer Engineering, M.S. in Electrical Engineering specializing in Robotics | Northwestern University Class of 2025
theme: jekyll-theme-minimal
